import { Inter } from '@next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="relative flex flex-col justify-center items-center">
          <p className="text-2xl font-bold text-center">
            Simulado 2 Bim
          </p>
        </div>

        <div className={styles.grid}>
          <Link
            href="/login"
            className={styles.button}
            
          >
            <h2 className={inter.className}>
              Login <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Entre na tela de login para acessar o sistema.
            </p>
          </Link>

          <Link
            href="/registro"
            className={styles.button}
            
          >
            <h2 className={inter.className}>
              Registro <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Ainda não tem uma conta? Acesse e registre-se agora
              mesmo!
            </p>
          </Link>

          <Link
            href="/recover"
            className={styles.button}
            
          >
            <h2 className={inter.className}>
              Recuperação de senha <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Esqueceu sua senha? Acesse e recupere sua senha
            </p>
          </Link>

          <Link
            href="/dashboard"
            className={styles.button}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Painel Principal <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Acesse para analisar os dados sobre algo
            </p>
          </Link>
        </div>
      </main>
    </>
  );
}
